export const ADD_RECIPE = "ADD_RECIPE"
export const UPDATE_RECIPE = "UPDATE_RECIPE"
export const SET_RECIPES = "SET_RECIPES";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const SET_ALL_RECIPES = "SET_ALL_RECIPES";

export const SET_USER = "SET_USER"
export const SET_AUTH_STATUS = "SET_AUTH_STATUS"

export const START_DRAG_RECIPE = "START_DRAG_RECIPE"
export const DROP_RECIPE = "DROP_RECIPE"
export const REMOVE_RECIPE = "REMOVE_RECIPE"
